"""Modified Review model

Revision ID: 5b9e3c26741f
Revises: a506219acd79
Create Date: 2023-10-10 11:15:46.337621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9e3c26741f'
down_revision = 'a506219acd79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=False))
        # Omitting the dropping of the foreign key constraint and customer_id column
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('date_posted')
        batch_op.drop_column('reviewer_name')
        # Omitting the re-adding of the customer_id column and its foreign key constraint
    # ### end Alembic commands ###
