"""Added customer_name and date_of_contract to Contract model

Revision ID: fa07bb294754
Revises: 5b625d686679
Create Date: 2023-10-08 18:52:13.834672

"""
from alembic import op
import sqlalchemy as sa
from datetime import date


# revision identifiers, used by Alembic.
revision = 'fa07bb294754'
down_revision = '5b625d686679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=False, server_default='Unknown Customer'))
        batch_op.add_column(sa.Column('date_of_contract', sa.Date(), nullable=False, server_default=date.today().isoformat()))

    
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.alter_column('customer_name', server_default=None)
        batch_op.alter_column('date_of_contract', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('date_of_contract')
        batch_op.drop_column('customer_name')
    # ### end Alembic commands ###
